### PR TITLE
Ability to specify function deployment namespace

### PR DESCRIPTION
**Pull request by weikinhuang**
Refs #20

### CODE REVIEW

**Comment by weikinhuang** [comment]
Combined with a helm chart, this should make it possible to split the control plane and the function deployments into separate namespaces via a an extra argument when running `faas-netes` deployment:

```yaml
apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: faas-netesd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: faas-netesd
    spec:
      serviceAccountName: faas-controller
      containers:
      - name: faas-netesd
        image: alexellis2/faas-netes:envvars
        command:
          - ./faas-netes
          - --function-namespace
          - faas-fn
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
```

**Comment by weikinhuang** [comment]
needs testing

**Comment by weikinhuang** [comment]
Tested with the following patch

```diff
diff --git i/faas.yml w/faas.yml
index 9e4dad4..c6575ce 100644
--- i/faas.yml
+++ w/faas.yml
@@ -2,6 +2,7 @@ apiVersion: v1
 kind: Service
 metadata:
   name: faas-netesd
+  namespace: openfaas
   labels:
     app: faas-netesd
 spec:
@@ -18,11 +19,19 @@ apiVersion: v1
 kind: ServiceAccount
 metadata:
   name: faas-controller
+  namespace: openfaas
+---
+apiVersion: v1
+kind: ServiceAccount
+metadata:
+  name: faas-controller
+  namespace: openfaas-fn
 ---
 apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
 kind: Deployment
 metadata:
   name: faas-netesd
+  namespace: openfaas
 spec:
   replicas: 1
   template:
@@ -33,7 +42,11 @@ spec:
       serviceAccountName: faas-controller
       containers:
       - name: faas-netesd
-        image: alexellis2/faas-netes:envvars
+        image: weikinhuang/faas-netes:function-ns
+        command:
+          - ./faas-netes
+          - --function-namespace
+          - openfaas-fn
         imagePullPolicy: Always
         ports:
         - containerPort: 8080
@@ -43,6 +56,7 @@ apiVersion: v1
 kind: Service
 metadata:
   name: gateway
+  namespace: openfaas
   labels:
     app: gateway
 spec:
@@ -59,6 +73,7 @@ apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
 kind: Deployment
 metadata:
   name: gateway
+  namespace: openfaas
 spec:
   replicas: 1
   template:
@@ -73,7 +88,7 @@ spec:
         imagePullPolicy: Always
         env:
         - name: functions_provider_url
-          value: "http://faas-netesd.default.svc.cluster.local:8080/"
+          value: "http://faas-netesd.openfaas.svc.cluster.local:8080/"
         ports:
         - containerPort: 8080
           protocol: TCP
diff --git i/monitoring.yml w/monitoring.yml
index 44659dd..903fad7 100644
--- i/monitoring.yml
+++ w/monitoring.yml
@@ -2,6 +2,7 @@ apiVersion: v1
 kind: Service
 metadata:
   name: prometheus
+  namespace: openfaas
   labels:
     app: prometheus
 spec:
@@ -18,6 +19,7 @@ apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
 kind: Deployment
 metadata:
   name: prometheus
+  namespace: openfaas
 spec:
   replicas: 1
   template:
@@ -28,16 +30,74 @@ spec:
       containers:
       - name: prometheus
         image: functions/prometheus:latest-k8s
-        command: ["prometheus","-config.file=/etc/prometheus/prometheus.yml", "-storage.local.path=/prometheus", "-storage.local.memory-chunks=10000", "--alertmanager.url=http://alertmanager.default:9093"]
+        command: ["prometheus","-config.file=/etc/prometheus/prometheus.yml", "-storage.local.path=/prometheus", "-storage.local.memory-chunks=10000", "--alertmanager.url=http://alertmanager:9093"]
         imagePullPolicy: Always
         ports:
         - containerPort: 9090
           protocol: TCP
+        volumeMounts:
+        - mountPath: /etc/prometheus/prometheus.yml
+          name: prometheus-config
+          subPath: prometheus.yml
+      volumes:
+        - name: prometheus-config
+          configMap:
+            name: prometheus-config
+            items:
+              - key: prometheus.yml
+                path: prometheus.yml
+                mode: 0644
+---
+kind: ConfigMap
+apiVersion: v1
+metadata:
+  name: prometheus-config
+  namespace: openfaas
+data:
+  prometheus.yml: |
+    # my global config
+    global:
+      scrape_interval:     15s # By default, scrape targets every 15 seconds.
+      evaluation_interval: 15s # By default, scrape targets every 15 seconds.
+      # scrape_timeout is set to the global default (10s).
+
+      # Attach these labels to any time series or alerts when communicating with
+      # external systems (federation, remote storage, Alertmanager).
+      external_labels:
+          monitor: 'faas-monitor'
+
+    # Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
+    rule_files:
+        - 'alert.rules'
+
+
+    # A scrape configuration containing exactly one endpoint to scrape:
+    # Here it's Prometheus itself.
+    scrape_configs:
+      # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
+      - job_name: 'prometheus'
+
+        # Override the global default and scrape targets from this job every 5 seconds.
+        scrape_interval: 5s
+
+        # metrics_path defaults to '/metrics'
+        # scheme defaults to 'http'.
+        static_configs:
+          - targets: ['localhost:9090']
+
+      - job_name: "gateway"
+        scrape_interval: 5s
+        dns_sd_configs:
+          - names: ['gateway.openfaas.svc.cluster.local']
+            port: 8080
+            type: A
+            refresh_interval: 5s
 ---
 apiVersion: v1
 kind: Service
 metadata:
   name: alertmanager
+  namespace: openfaas
   labels:
     app: alertmanager
 spec:
@@ -54,6 +114,7 @@ apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
 kind: Deployment
 metadata:
   name: alertmanager
+  namespace: openfaas
 spec:
   replicas: 1
   template:
diff --git i/rbac.yml w/rbac.yml
index d056691..3bf4f27 100644
--- i/rbac.yml
+++ w/rbac.yml
@@ -30,6 +30,7 @@ apiVersion: rbac.authorization.k8s.io/v1beta1
 kind: ClusterRoleBinding
 metadata:
   name: faas-controller
+  namespace: openfaas
 roleRef:
   apiGroup: rbac.authorization.k8s.io
   kind: ClusterRole
@@ -37,4 +38,18 @@ roleRef:
 subjects:
 - kind: ServiceAccount
   name: faas-controller
-  namespace: default
+  namespace: openfaas
+---
+apiVersion: rbac.authorization.k8s.io/v1beta1
+kind: ClusterRoleBinding
+metadata:
+  name: faas-controller
+  namespace: openfaas-fn
+roleRef:
+  apiGroup: rbac.authorization.k8s.io
+  kind: ClusterRole
+  name: faas-controller
+subjects:
+- kind: ServiceAccount
+  name: faas-controller
+  namespace: openfaas
```

**Comment by weikinhuang** [comment]
```bash
$ kubectl get -n openfaas deploy,cm,cronjob,pvc,secret,svc,po
NAME                  DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/alertmanager   1         1         1            1           17m
deploy/faas-netesd    1         1         1            1           17m
deploy/gateway        1         1         1            1           17m
deploy/prometheus     1         1         1            1           17m

NAME                   DATA      AGE
cm/prometheus-config   1         4m

NAME                                  TYPE                                  DATA      AGE
secrets/default-token-s6vb1           kubernetes.io/service-account-token   3         23m
secrets/faas-controller-token-g32cj   kubernetes.io/service-account-token   3         18m

NAME               CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
svc/alertmanager   10.3.59.159    <nodes>       9093:31113/TCP   17m
svc/faas-netesd    10.3.252.112   <nodes>       8080:31111/TCP   18m
svc/gateway        10.3.16.61     <nodes>       8080:31112/TCP   17m
svc/prometheus     10.3.240.43    <nodes>       9090:31119/TCP   17m

NAME                               READY     STATUS    RESTARTS   AGE
po/alertmanager-4083991118-w0s0r   1/1       Running   0          17m
po/faas-netesd-2288097303-fjdlx    1/1       Running   0          14m
po/gateway-2697391564-gj02q        1/1       Running   0          17m
po/prometheus-766498443-h2sqd      1/1       Running   0          4m


$ kubectl get -n openfaas-fn deploy,cm,cronjob,pvc,secret,svc,po
NAME              DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/nodeinfo   1         1         1            1           12m

NAME                                  TYPE                                  DATA      AGE
secrets/default-token-h92z4           kubernetes.io/service-account-token   3         23m
secrets/faas-controller-token-008w3   kubernetes.io/service-account-token   3         18m

NAME           CLUSTER-IP    EXTERNAL-IP   PORT(S)    AGE
svc/nodeinfo   10.3.175.68   <none>        8080/TCP   12m

NAME                           READY     STATUS    RESTARTS   AGE
po/nodeinfo-2445776822-pm9m9   1/1       Running   0          12m
```

**Comment by alexellis** [comment]
Can we configure the namespace via environmental variable instead of flag and set a default for when it's not available?

**Comment by alexellis** [comment]
> +          - names: ['gateway.openfaas.svc.cluster.local']

This is hard-coded - so how do we configure Prometheus (easily) for each of the different namespaces in the cluster?

**Comment by weikinhuang** [comment]
Yes, once we have a helm chart, the namespaces would all be template variables

**Comment by weikinhuang** [comment]
In my patch file for testing, I pulled the prometheus config out into a configmap so we can template the contents once we can.

**Pull request merged**
